version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image
  
  category-service:
    build: ./category-service
    environment:
      DB_HOST: web-shop-db-image
    ports:
      - "3000:3000"
    depends_on:
      web-shop-db-image:
        condition: service_healthy
    networks:
        local_dev_net:
            aliases:  
                - category-service

  productservice:
    build: ./productservice
    environment:
      DB_HOST: web-shop-db-image
      CATEGORY_SERVICE_HOST: category-service
    ports:
      - "8000:8000"
    depends_on:
      web-shop-db-image:
        condition: service_healthy
    networks:
      local_dev_net:
        aliases:
          - productservice

networks:
  local_dev_net:
    driver: bridge
