version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    environment:
      CATEGORY_SERVICE: http://category-service:3000
      PRODUCT_SERVICE: http://productservice:8000/api/v1
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  mysql:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
        local_dev_net:
            aliases:
                - mysql
  
  category-service:
    build: ./category-service
    environment:
      DB_HOST: mysql
      PRODUCT_SERVICE_ADRESS: http://productservice:8000/api/v1/products/category
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
        local_dev_net:
            aliases:  
                - category-service

  productservice:
    build:
      context: ./productservice
      target: prod
    environment:
      DB_HOST: mysql
      CUSTOM_CATEGORY_SERVICE_HOST: category-service
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      local_dev_net:
        aliases:
          - productservice

networks:
  local_dev_net:
    driver: bridge
