apiVersion: v1
kind: Service
metadata:
  labels:
    app: category-service
  name: category-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: category-service