apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer
  selector:
    app: product-service