name: Build and upload images
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
      packages: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push category-service
        uses: docker/build-push-action@v4
        with:
          context: category-service/
          push: true
          pull: true
          tags:  ghcr.io/${{ github.repository }}/category-service
      - name: Build and push product-service
        uses: docker/build-push-action@v4
        with:
          context: productservice/
          push: true
          pull: true
          tags:  ghcr.io/${{ github.repository }}/productservice
      - name: Build and push mysql
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: docker/DockerfileMySQL
          push: true
          pull: true
          tags:  ghcr.io/${{ github.repository }}/mysql
      - name: Build and push legacy web service
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: docker/Dockerfile
          push: true
          pull: true
          tags:  ghcr.io/${{ github.repository }}/legacy-web-service
